// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApovAp1nmFA-i8QjobDeAgvTGua1_B1DE',
    appId: '1:1087163474092:web:b64d06d9c2a9245710ff09',
    messagingSenderId: '1087163474092',
    projectId: 'push-notification-2f088',
    authDomain: 'push-notification-2f088.firebaseapp.com',
    storageBucket: 'push-notification-2f088.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLKm8Xybw9kTwp8fd1WiQUbFOK91hvY88',
    appId: '1:1087163474092:android:bb92f0b4d8a2d45b10ff09',
    messagingSenderId: '1087163474092',
    projectId: 'push-notification-2f088',
    storageBucket: 'push-notification-2f088.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPJFf6odr__Kese4S2zV3m1TQg_Di3j4Y',
    appId: '1:1087163474092:ios:5b189c6ad17e579810ff09',
    messagingSenderId: '1087163474092',
    projectId: 'push-notification-2f088',
    storageBucket: 'push-notification-2f088.appspot.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPJFf6odr__Kese4S2zV3m1TQg_Di3j4Y',
    appId: '1:1087163474092:ios:699f56d0a634d10110ff09',
    messagingSenderId: '1087163474092',
    projectId: 'push-notification-2f088',
    storageBucket: 'push-notification-2f088.appspot.com',
    iosBundleId: 'com.example.task.RunnerTests',
  );
}
